from __future__ import annotations

import hashlib
import random

from .models import MusicParameters, Persona, ReactionOutput, TimeStage

_VOLUME_LEVEL = {"low": 2, "medium": 5, "high": 8}


def stable_seed(persona_id: str, scene: str, music: MusicParameters) -> int:
    raw = f"{persona_id}|{scene}|{music.model_dump_json()}".encode("utf-8")
    return int(hashlib.sha256(raw).hexdigest()[:8], 16)


def _clamp(value: float) -> int:
    return max(1, min(10, round(value)))


def simulate(persona: Persona, music: MusicParameters, scene: str) -> tuple[ReactionOutput, int]:
    """Create a reproducible software fixture, not a clinical prediction."""
    seed = stable_seed(persona.persona_id, scene, music)
    rng = random.Random(seed)

    auditory = persona.sensory_profile.auditory_sensitivity
    seeking = persona.sensory_profile.sensory_seeking
    change = persona.sensory_profile.change_sensitivity
    volume_pressure = _VOLUME_LEVEL[music.volume]
    tempo_distance = abs(music.bpm - (85 if seeking >= 7 else 62)) / 12
    abruptness = 2 if music.tonality == "atonal" else 0
    lyric_load = 2 if music.lyrics_language != "none" else 0

    anxiety = _clamp(2 + 0.55 * auditory + 0.45 * volume_pressure + 0.35 * tempo_distance + abruptness + 0.25 * lyric_load - 4)
    engagement = _clamp(4 + 0.6 * seeking - 0.35 * tempo_distance - 0.35 * anxiety + rng.uniform(-0.8, 0.8))

    if music.instrument == "percussion" and seeking >= 7:
        engagement = _clamp(engagement + 2)
    if music.volume == "high" and auditory >= 7:
        anxiety = _clamp(anxiety + 2)
        engagement = _clamp(engagement - 2)
    if change >= 8 and music.tonality == "atonal":
        anxiety = _clamp(anxiety + 1)

    mood = _clamp(5 + 0.45 * engagement - 0.45 * anxiety + rng.uniform(-0.6, 0.6))
    regulation = _clamp(6 + 0.4 * mood - 0.55 * anxiety + (1 if music.volume == "low" else 0))
    attention = max(15, min(music.duration_sec, int(music.duration_sec * (0.35 + engagement / 16))))

    start_a = _clamp(anxiety + (1 if change >= 7 else 0))
    middle_a = _clamp((start_a + anxiety) / 2)
    end_a = anxiety
    start_e = _clamp(engagement - 1)
    middle_e = engagement
    end_e = _clamp(engagement + (1 if regulation >= 7 else -1 if anxiety >= 8 else 0))

    flags: list[str] = []
    if anxiety >= 8:
        flags.append("high simulated distress score; stop-condition should be shown")
    if music.volume == "high":
        flags.append("high-volume setting requires explicit caution")

    reaction = ReactionOutput(
        anxiety_level=anxiety,
        engagement_level=engagement,
        mood_score=mood,
        regulation_score=regulation,
        attention_duration_sec=attention,
        physical_observations=[
            "Synthetic posture/movement observation generated by deterministic rules.",
            "No inference about a real child should be made from this output.",
        ],
        communication_observations=[
            "Synthetic communication response is constrained by the persona's listed modes."
        ],
        time_series=[
            TimeStage(stage="start", observation="Initial orientation to sound.", anxiety_level=start_a, engagement_level=start_e),
            TimeStage(stage="middle", observation="Response after the pattern becomes more predictable.", anxiety_level=middle_a, engagement_level=middle_e),
            TimeStage(stage="end", observation="State at the end of the configured trial.", anxiety_level=end_a, engagement_level=end_e),
        ],
        research_notes=(
            "Rule-based reference output for software testing. Scores are constructed from the synthetic "
            "profile and music parameters; they are not validated clinical measures."
        ),
        uncertainty_note="High uncertainty: this is a fictional, deterministic teaching model.",
        safety_flags=flags,
    )
    return reaction, seed
